version: '3.8'

services:
  sap-academy-app:
    build: .
    container_name: sap-academy-web
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
    volumes:
      # Mountet den Projektordner live in den Container
      - .:/var/www/html
      # Überschreibt die Apache-Konfiguration zwingend mit der lokalen Datei
      - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf